# Helper function
command_exists () {
    type "$1" &> /dev/null ;
}

# What OS are we running?
# TODO: Cope with cygwin
export platform=$(uname)
if [[ $platform == "Darwin" ]] ; then
	platform='OSX'
elif [[ $platform == 'Linux' ]] ; then
	if command_exists apt-get ; then
		platform='deb-like'
	elif command_exists rpm ; then
		platform='redhat-like'
	elif command_exists pacman ; then
		platform='arch-like'
	else 
		platform='unknown-linux'
	fi
fi

#
#Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
if [[ $platform == "OSX" ]] ; then
		ZSH_THEME="theunraveler"
elif [[ $platform == "deb-like" ]] ; then 
		ZSH_THEME="agnoster"
else
		ZSH_THEME="random"
		echo "No theme set up for this setup! Going random. Edit zshrc to fix."
fi

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

source $ZSH/oh-my-zsh.sh

export LANG=en_GB.UTF-8

# Some VPS stuff
# For reference, the IP of the vps is 207.210.193.250, just in case there's a DNS issue.
alias vps="ssh -l tom probablytom.ddns.net"

# Some editor config stuff
alias emacs="emacs -nw"
export EDITOR="vim"
if command_exists nvim ; then
    alias vim="nvim"
fi
export TERM=xterm-256color

# For commandline media playing
if command_exists mpv ; then
    alias play="mpv --no-audio-display"
elif command_exists mplayer ; then
    alias play="mplayer"
else
		# We don't have a music player installed.
		if [[platform == 'OSX']] ; then
				if command_exists brew ; then
						# Offer to install mpv
				else
						# Offer to install brew and mpv
				fi
		fi  # Change to elif to manage linux options
fi

alias sort_music="python ~/.rcfiles/scripts/music_organizer.py"
